site_name: ACME Docs
site_url: https://zshupp.github.io/acme-docs/
repo_name: acme-docs
repo_url: https://github.com/zshupp/acme-docs
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes 
    - navigation.top

plugins:
  - search